### ISSUE TITLE
nested worktrees error

### ISSUE THREAD

**Issue by davidsmorais** [yankeexe/git-worktree-switcher#10]
Hey :wave: 
Great tool you've built, congratz :tada: 

It works great for changing directories across worktrees, however, if I try to change to a nested worktree like `feature/something-something` I get this error:

![image](https://user-images.githubusercontent.com/22729436/158992306-450ac6c8-3aa0-438c-9840-9c15687568e0.png)

Is this something in my setup, or is it an error with the script itself not being ready to support / separated wt names ?

**Comment by yankeexe** [comment]
Hey @davidsmorais thanks for raising this issue. Yes, this looks like an issue when you add search words with forward slash `/` for worktree names.

We do fuzzy match to figure out the worktree name based on whatever words we type (you don't have to type the whole worktree name). For example: 
![image](https://user-images.githubusercontent.com/13623913/159111590-f0c2b4c8-725e-4e14-a6ea-c84b403c6e98.png)

But if you want to type the whole path, I will create a fix for it on the next release.

**Comment by yankeexe** [comment]
Fixed by release https://github.com/yankeexe/git-worktree-switcher/releases/tag/0.1.0

Update to the latest version for the fix: 
```sh 
wt update
```

**Comment by davidsmorais** [comment]
> We do fuzzy match to figure out the worktree name based on whatever words we type (you don't have to type the whole worktree name). For example:

Even better, awesome :rocket: 

Thank you for the fast reply & switf action, keep up the awesome work :clap:
