### ISSUE TITLE
wt creates a new shell every time it is run

### ISSUE THREAD

**Issue by ghgary** [yankeexe/git-worktree-switcher#11]
Soon after starting to use wt, I discovered that it was creating a new shell every time it was run. A better way to cd from a command is to make that command a function, as ranger and wcd do. I created such a function and modified the wt script to write the new directory to a file rather than cd to it itself.

Here is the function, which should be in the user's ~/.bashrc or in /etc/profile.d/wt.sh.

```
type -f wt &> /dev/null &&
wt()
{
    local dirfile="$HOME/.wt.dir"
    rm -f "$dirfile"
    command wt "$@"
    if [ -f "$dirfile" ]; then
	if [ "$(< "$dirfile")" != "$(pwd)" ]; then
	    cd -- "$(< "$dirfile")"
	fi
    fi
}
```

I also discovered that wt uses grep with Perl regular expressions, which isn't supported by some distributions' greps. Since wt uses awk already, I just moved the processing that grep was doing inside the awk command and removed grep.

The awk pattern used to find the new worktree allowed the match to occur on lines other than those that began with "worktree", which caused odd errors if the user made an error in the worktree name, so I fixed that, too.

Here is a diff of my changes.

```
diff --git a/wt b/wt
index 0f79eaa..c76c715 100755
--- a/wt
+++ b/wt
@@ -10,6 +10,7 @@ BINARY_PATH=$(which wt)
 JQ_URL="https://stedolan.github.io/jq/download"
 RELEASE_URL="https://github.com/yankeexe/git-worktree-switcher/releases/latest"
 RELEASE_API_URL="https://api.github.com/repos/yankeexe/git-worktree-switcher/releases/latest"
+dirfile="$HOME/.wt.dir"


 # Escape forward slash
@@ -31,14 +32,13 @@ help_message() {
 }

 goto_main_worktree() {
-       main_worktree=$(git worktree list --porcelain | awk '{print $0; exit}' | grep -oP '(?<=worktree ).*')
+       main_worktree=$(git worktree list --porcelain | awk '{sub("worktree ", ""); print; exit}')

        if [ -z "$main_worktree" ]; then
                :
        else
                echo Changing to main worktree at: "$main_worktree"
-               cd "$main_worktree"
-               exec $SHELL
+               echo "$main_worktree" > "$dirfile"
        fi
 }

@@ -99,15 +99,14 @@ version)
        goto_main_worktree
        ;;
 *)
-       directory=$(git worktree list --porcelain | awk '/'"$arg"'/ {print; exit}' | grep -oP '(?<=worktree ).*')
+       directory=$(git worktree list --porcelain | awk '/^worktree .*'"$arg"'/ {sub("worktree ", ""); print; exit}')
        ;;
 esac

 # Change worktree based on user argument.
 change_worktree() {
        echo Changing to worktree at: "$directory"
-       cd "$directory"
-       exec $SHELL
+       echo "$directory" > "$dirfile"
 }

 # If directory variable is not empty then change worktree
```

Wt is working great now. Thanks for the script and for the article on using worktrees.

Regards,
Gary

**Comment by CodeBleu** [comment]
@ghgary nice write up of issues.  Maybe if you submit a pull request, the owner will merge these fixes in. :crossed_fingers:

**Comment by yankeexe** [comment]
@ghgary please send a PR related to this issue, I would love to have this work without creating a new shell
