### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by dlvhdr** [yankeexe/git-worktree-switcher#7]
Love the script!
I would also love if I could autocomplete the work-trees names, so I wouldn't have to do `wt list`.

**Comment by yankeexe** [comment]
@dlvhdr that sounds like an interesting idea. Are you looking to contribute the feature? :slightly_smiling_face:

**Comment by dlvhdr** [comment]
Yeah possibly. Just need to find the time 😅

**Comment by yankeexe** [comment]
Hey @dlvhdr just added auto-completion for bash; can you take it for a spin? :smile: 

https://github.com/yankeexe/git-worktree-switcher/commit/14cb73ee681a999980764740da92bc487bfedf86

You can find the instructions here: https://github.com/yankeexe/git-worktree-switcher#tab-completion :slightly_smiling_face:

**Comment by dlvhdr** [comment]
Thanks for doing it so fast!
I'm using zsh so not sure if this is relevant, but the autocompletions only work when I'm at the root level.
I'm also using git bare repo, if that's relevant.

https://user-images.githubusercontent.com/6196971/150637137-fedbd2aa-4769-4324-9c46-9c7788aa6eeb.mov

**Comment by yankeexe** [comment]
@dlvhdr  Can you add these lines at the top of your zshrc? 

```bash
autoload bashcompinit && bashcompinit 

source <path-to-wt_completion> 
```

and  source  your  zshrc file, let me know if it works :slightly_smiling_face:

**Comment by dlvhdr** [comment]
This works! Thanks for the help

**Comment by yankeexe** [comment]
Hey @dlvhdr added native zsh autocompletion script on the new release:  :slightly_smiling_face: 
https://github.com/yankeexe/git-worktree-switcher/releases/tag/0.0.5
